/**
 * Profile README Generator
 *
 * Fetches live GitHub stats via the unauthenticated REST API and generates
 * a Markdown profile README (`james-profile.md`) suitable for copying into
 * jtmb/jtmb (the special profile repo).
 *
 * Run: npx tsx scripts/generate-profile-readme.ts
 */
import fs from "fs";
import path from "path";

const GITHUB_USER = "jtmb";
const API_BASE = "https://api.github.com";

interface Repo {
  name: string;
  description: string | null;
  stargazers_count: number;
  language: string | null;
  fork: boolean;
  archived: boolean;
  topics: string[];
  html_url: string;
}

interface GitHubUser {
  public_repos: number;
  followers: number;
  following: number;
  bio: string | null;
  avatar_url: string;
  name: string | null;
  location: string | null;
  html_url: string;
}

/** Fetch with timeout and error handling */
async function ghFetch<T>(endpoint: string): Promise<T | null> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10_000);

  try {
    const res = await fetch(`${API_BASE}${endpoint}`, {
      headers: { Accept: "application/vnd.github.v3+json" },
      signal: controller.signal,
    });

    if (!res.ok) {
      console.error(`  ⚠ ${endpoint} → ${res.status}`);
      return null;
    }

    return (await res.json()) as T;
  } catch (err) {
    console.error(`  ⚠ ${endpoint} → ${err instanceof Error ? err.message : err}`);
    return null;
  } finally {
    clearTimeout(timeout);
  }
}

function escapeMarkdown(text: string): string {
  return text.replace(/([*_{}[\]()#+\-.!`|\\])/g, "\\$1");
}

function generateReadme(user: GitHubUser, repos: Repo[]): string {
  const nonFork = repos.filter((r) => !r.fork && !r.archived);
  const totalStars = repos.reduce((sum, r) => sum + r.stargazers_count, 0);

  // Count top languages
  const langCount: Record<string, number> = {};
  for (const r of nonFork) {
    if (r.language) {
      langCount[r.language] = (langCount[r.language] || 0) + 1;
    }
  }
  const topLanguages = Object.entries(langCount)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 8);

  // Top 6 starred repos
  const topRepoList = [...nonFork]
    .sort((a, b) => b.stargazers_count - a.stargazers_count)
    .slice(0, 6);

  const topRepos = topRepoList
    .map(
      (r) =>
        `- [**${escapeMarkdown(r.name)}**](${r.html_url}) — ${escapeMarkdown(r.description || "No description")} ${r.stargazers_count > 0 ? `⭐ ${r.stargazers_count}` : ""}`,
    )
    .join("\n");

  const languageBadges = topLanguages
    .map(([lang, count]) => `\`${escapeMarkdown(lang)}\``)
    .join(" ");

  const mostRecentRepos = repos
    .filter((r) => !r.fork && !r.archived)
    .slice(0, 6)
    .map((r) => `- [**${escapeMarkdown(r.name)}**](${r.html_url}) — ${escapeMarkdown(r.description || "No description")}`)
    .join("\n");

  const now = new Date();
  const updatedAt = now.toISOString().replace("T", " ").slice(0, 19);

  return `<!-- ⚡ GENERATED by scripts/generate-profile-readme.ts — DO NOT EDIT DIRECTLY -->
<!-- Last updated: ${updatedAt} UTC -->

<h1 align="center">
  <img src="https://raw.githubusercontent.com/jtmb/jtmb/main/avatar.png" width="100" height="100" style="border-radius: 50%;" alt="James" />
  <br/>
  Hey there! I'm <strong>${escapeMarkdown(user.name || GITHUB_USER)}</strong> 👋
</h1>

<p align="center">
  <em>${escapeMarkdown(user.bio || "DevOps engineer, homelab enthusiast, and open source contributor.")}</em>
</p>

<p align="center">
  <a href="${user.html_url}"><img src="https://img.shields.io/badge/GitHub-${GITHUB_USER}-181717?logo=github&style=flat-square" alt="GitHub" /></a>
  <a href="https://${GITHUB_USER}.dev"><img src="https://img.shields.io/badge/Portfolio-${GITHUB_USER}.dev-6366f1?logo=vercel&style=flat-square" alt="Portfolio" /></a>
</p>

---

## 📊 Stats

<p align="center">
  <img src="https://img.shields.io/badge/Public%20Repos-${user.public_repos}-blue?logo=github&style=for-the-badge" alt="Public Repos" />
  <img src="https://img.shields.io/badge/Stars-${totalStars}-yellow?logo=github&style=for-the-badge" alt="Stars" />
  <img src="https://img.shields.io/badge/Followers-${user.followers}-lightgrey?logo=github&style=for-the-badge" alt="Followers" />
</p>

<details>
<summary>📈 GitHub Activity</summary>
<br/>
<p align="center">
  <img src="https://github-readme-stats.vercel.app/api?username=${GITHUB_USER}&show_icons=true&theme=default&hide_border=true&count_private=false&include_all_commits=true" alt="GitHub Stats" width="450" />
  <img src="https://github-readme-streak-stats.herokuapp.com/?user=${GITHUB_USER}&theme=default&hide_border=true" alt="GitHub Streak" width="450" />
</p>
</details>

---

## 🛠️ Tech I Work With

<p align="center">
  ${languageBadges}
</p>

### 🏗️ Featured Projects

<p align="center">
  <a href="https://github.com/jtmb/arr-stack-4-dummies"><img src="https://github-readme-stats.vercel.app/api/pin/?username=${GITHUB_USER}&repo=arr-stack-4-dummies&theme=default&hide_border=true" alt="arr-stack-4-dummies" /></a>
  <a href="https://github.com/jtmb/branconet-homelab"><img src="https://github-readme-stats.vercel.app/api/pin/?username=${GITHUB_USER}&repo=branconet-homelab&theme=default&hide_border=true" alt="branconet-homelab" /></a>
  <a href="https://github.com/jtmb/ansible-rke2-rancher"><img src="https://github-readme-stats.vercel.app/api/pin/?username=${GITHUB_USER}&repo=ansible-rke2-rancher&theme=default&hide_border=true" alt="ansible-rke2-rancher" /></a>
  <a href="https://github.com/jtmb/ez-backups"><img src="https://github-readme-stats.vercel.app/api/pin/?username=${GITHUB_USER}&repo=ez-backups&theme=default&hide_border=true" alt="ez-backups" /></a>
</p>

---

## 🚀 Top Repos

${topRepos}

---

## 📝 Latest Work

${mostRecentRepos}

---

## 📫 Let's Connect

<p align="center">
  <a href="${user.html_url}"><img src="https://img.shields.io/badge/GitHub-${GITHUB_USER}-181717?logo=github&style=for-the-badge" alt="GitHub" /></a>
  <a href="https://${GITHUB_USER}.dev"><img src="https://img.shields.io/badge/Portfolio-${GITHUB_USER}.dev-6366f1?logo=vercel&style=for-the-badge" alt="Portfolio" /></a>
</p>

---

<p align="center">
  <sub>⚡ This README is auto-generated every 6 hours. Last updated: ${updatedAt} UTC</sub>
</p>`;
}

async function main() {
  console.log("🔍 Fetching GitHub data for", GITHUB_USER, "...\n");

  // Fetch user profile
  console.log("  Fetching user profile...");
  const user = await ghFetch<GitHubUser>(`/users/${GITHUB_USER}`);
  if (!user) {
    console.error("❌ Failed to fetch user profile. Aborting.");
    process.exit(1);
  }
  console.log(`  ✓ ${user.name || GITHUB_USER} — ${user.public_repos} repos, ${user.followers} followers\n`);

  // Fetch all repos (public, no keys needed)
  console.log("  Fetching repositories...");
  const repos = await ghFetch<Repo[]>(`/users/${GITHUB_USER}/repos?per_page=100&sort=updated`);
  if (!repos) {
    console.error("❌ Failed to fetch repos. Aborting.");
    process.exit(1);
  }
  console.log(`  ✓ ${repos.length} repos fetched\n`);

  // Generate README
  console.log("  Generating README...");
  const readme = generateReadme(user, repos);

  const outPath = path.join(process.cwd(), "james-profile.md");
  fs.writeFileSync(outPath, readme, "utf-8");
  console.log(`  ✓ Written to ${outPath} (${readme.length.toLocaleString()} bytes)`);

  // Print summary stats
  const nonFork = repos.filter((r) => !r.fork && !r.archived);
  const totalStars = repos.reduce((sum, r) => sum + r.stargazers_count, 0);

  console.log("\n📊 Summary:");
  console.log(`  Repos:              ${nonFork.length} (excluding forks/archived)`);
  console.log(`  Stars:              ${totalStars}`);
  console.log(`  Followers:          ${user.followers}`);

  console.log("\n✅ Done! Copy james-profile.md → jtmb/jtmb/README.md");
}

main().catch((err) => {
  console.error("❌ Fatal error:", err);
  process.exit(1);
});
